version: '3.8'

services:
  mysql-container:
    image: mysql:latest
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: toeicmimidb
      MYSQL_DATABASE: monodb
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql

  minio:
    image: minio/minio:latest
    container_name: minio-container
    restart: always
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    ports:
      - "9000:9000"      # MinIO API
      - "9001:9001"      # MinIO Console
    volumes:
      - ./minio-data:/data
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

volumes:
  mysql-data:
    driver: local
  minio-data:
    driver: local